(cl:defpackage nao_msgs-srv
  (:use )
  (:export
   "GETTRUEPOSE"
   "<GETTRUEPOSE-REQUEST>"
   "GETTRUEPOSE-REQUEST"
   "<GETTRUEPOSE-RESPONSE>"
   "GETTRUEPOSE-RESPONSE"
   "GETINSTALLEDBEHAVIORS"
   "<GETINSTALLEDBEHAVIORS-REQUEST>"
   "GETINSTALLEDBEHAVIORS-REQUEST"
   "<GETINSTALLEDBEHAVIORS-RESPONSE>"
   "GETINSTALLEDBEHAVIORS-RESPONSE"
   "CMDVELSERVICE"
   "<CMDVELSERVICE-REQUEST>"
   "CMDVELSERVICE-REQUEST"
   "<CMDVELSERVICE-RESPONSE>"
   "CMDVELSERVICE-RESPONSE"
   "CMDPOSESERVICE"
   "<CMDPOSESERVICE-REQUEST>"
   "CMDPOSESERVICE-REQUEST"
   "<CMDPOSESERVICE-RESPONSE>"
   "CMDPOSESERVICE-RESPONSE"
  ))

