/* Auto-generated by genmsg_cpp for file /home/rob/ros_workspace/rosmodules/nao/stacks/nao_robot/nao_msgs/msg/BodyPoseGoal.msg */
#ifndef NAO_MSGS_MESSAGE_BODYPOSEGOAL_H
#define NAO_MSGS_MESSAGE_BODYPOSEGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace nao_msgs
{
template <class ContainerAllocator>
struct BodyPoseGoal_ {
  typedef BodyPoseGoal_<ContainerAllocator> Type;

  BodyPoseGoal_()
  : pose_name()
  {
  }

  BodyPoseGoal_(const ContainerAllocator& _alloc)
  : pose_name(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pose_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  pose_name;


  typedef boost::shared_ptr< ::nao_msgs::BodyPoseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_msgs::BodyPoseGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BodyPoseGoal
typedef  ::nao_msgs::BodyPoseGoal_<std::allocator<void> > BodyPoseGoal;

typedef boost::shared_ptr< ::nao_msgs::BodyPoseGoal> BodyPoseGoalPtr;
typedef boost::shared_ptr< ::nao_msgs::BodyPoseGoal const> BodyPoseGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nao_msgs::BodyPoseGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nao_msgs::BodyPoseGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nao_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::BodyPoseGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::BodyPoseGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_msgs::BodyPoseGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e6184073e8e665fb2bf0be194fc36541";
  }

  static const char* value(const  ::nao_msgs::BodyPoseGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe6184073e8e665fbULL;
  static const uint64_t static_value2 = 0x2bf0be194fc36541ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_msgs::BodyPoseGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_msgs/BodyPoseGoal";
  }

  static const char* value(const  ::nao_msgs::BodyPoseGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_msgs::BodyPoseGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal: a registered body pose name\n\
string pose_name\n\
\n\
";
  }

  static const char* value(const  ::nao_msgs::BodyPoseGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_msgs::BodyPoseGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pose_name);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BodyPoseGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_msgs::BodyPoseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nao_msgs::BodyPoseGoal_<ContainerAllocator> & v) 
  {
    s << indent << "pose_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pose_name);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NAO_MSGS_MESSAGE_BODYPOSEGOAL_H

