/* Auto-generated by genmsg_cpp for file /home/rob/ros_workspace/rosmodules/nao/stacks/nao_robot/nao_msgs/msg/FollowPathFeedback.msg */
#ifndef NAO_MSGS_MESSAGE_FOLLOWPATHFEEDBACK_H
#define NAO_MSGS_MESSAGE_FOLLOWPATHFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace nao_msgs
{
template <class ContainerAllocator>
struct FollowPathFeedback_ {
  typedef FollowPathFeedback_<ContainerAllocator> Type;

  FollowPathFeedback_()
  : index(0)
  {
  }

  FollowPathFeedback_(const ContainerAllocator& _alloc)
  : index(0)
  {
  }

  typedef uint32_t _index_type;
  uint32_t index;


  typedef boost::shared_ptr< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_msgs::FollowPathFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FollowPathFeedback
typedef  ::nao_msgs::FollowPathFeedback_<std::allocator<void> > FollowPathFeedback;

typedef boost::shared_ptr< ::nao_msgs::FollowPathFeedback> FollowPathFeedbackPtr;
typedef boost::shared_ptr< ::nao_msgs::FollowPathFeedback const> FollowPathFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nao_msgs::FollowPathFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nao_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::FollowPathFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ad7b979103dbd563a352ef5270716728";
  }

  static const char* value(const  ::nao_msgs::FollowPathFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xad7b979103dbd563ULL;
  static const uint64_t static_value2 = 0xa352ef5270716728ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_msgs/FollowPathFeedback";
  }

  static const char* value(const  ::nao_msgs::FollowPathFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback: index of current subgoal in path\n\
uint32 index\n\
\n\
\n\
";
  }

  static const char* value(const  ::nao_msgs::FollowPathFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.index);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FollowPathFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_msgs::FollowPathFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nao_msgs::FollowPathFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.index);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NAO_MSGS_MESSAGE_FOLLOWPATHFEEDBACK_H

