/* Auto-generated by genmsg_cpp for file /home/rob/ros_workspace/rosmodules/nao/stacks/nao_robot/nao_msgs/msg/JointAnglesWithSpeedResult.msg */
#ifndef NAO_MSGS_MESSAGE_JOINTANGLESWITHSPEEDRESULT_H
#define NAO_MSGS_MESSAGE_JOINTANGLESWITHSPEEDRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "sensor_msgs/JointState.h"

namespace nao_msgs
{
template <class ContainerAllocator>
struct JointAnglesWithSpeedResult_ {
  typedef JointAnglesWithSpeedResult_<ContainerAllocator> Type;

  JointAnglesWithSpeedResult_()
  : goal_position()
  {
  }

  JointAnglesWithSpeedResult_(const ContainerAllocator& _alloc)
  : goal_position(_alloc)
  {
  }

  typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _goal_position_type;
   ::sensor_msgs::JointState_<ContainerAllocator>  goal_position;


  typedef boost::shared_ptr< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct JointAnglesWithSpeedResult
typedef  ::nao_msgs::JointAnglesWithSpeedResult_<std::allocator<void> > JointAnglesWithSpeedResult;

typedef boost::shared_ptr< ::nao_msgs::JointAnglesWithSpeedResult> JointAnglesWithSpeedResultPtr;
typedef boost::shared_ptr< ::nao_msgs::JointAnglesWithSpeedResult const> JointAnglesWithSpeedResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nao_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1c77b3d9dc137611510fd16c3b792046";
  }

  static const char* value(const  ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1c77b3d9dc137611ULL;
  static const uint64_t static_value2 = 0x510fd16c3b792046ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_msgs/JointAnglesWithSpeedResult";
  }

  static const char* value(const  ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# result is the actually reached position\n\
sensor_msgs/JointState goal_position\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.goal_position);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointAnglesWithSpeedResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nao_msgs::JointAnglesWithSpeedResult_<ContainerAllocator> & v) 
  {
    s << indent << "goal_position: ";
s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_position);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NAO_MSGS_MESSAGE_JOINTANGLESWITHSPEEDRESULT_H

