/* Auto-generated by genmsg_cpp for file /home/rob/ros_workspace/rosmodules/nao/stacks/nao_robot/nao_msgs/msg/RunBehaviorResult.msg */
#ifndef NAO_MSGS_MESSAGE_RUNBEHAVIORRESULT_H
#define NAO_MSGS_MESSAGE_RUNBEHAVIORRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace nao_msgs
{
template <class ContainerAllocator>
struct RunBehaviorResult_ {
  typedef RunBehaviorResult_<ContainerAllocator> Type;

  RunBehaviorResult_()
  : noErrors(false)
  {
  }

  RunBehaviorResult_(const ContainerAllocator& _alloc)
  : noErrors(false)
  {
  }

  typedef uint8_t _noErrors_type;
  uint8_t noErrors;


  typedef boost::shared_ptr< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_msgs::RunBehaviorResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RunBehaviorResult
typedef  ::nao_msgs::RunBehaviorResult_<std::allocator<void> > RunBehaviorResult;

typedef boost::shared_ptr< ::nao_msgs::RunBehaviorResult> RunBehaviorResultPtr;
typedef boost::shared_ptr< ::nao_msgs::RunBehaviorResult const> RunBehaviorResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nao_msgs::RunBehaviorResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nao_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::RunBehaviorResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e6b2d7551eb5c957b430b0edca37c8db";
  }

  static const char* value(const  ::nao_msgs::RunBehaviorResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe6b2d7551eb5c957ULL;
  static const uint64_t static_value2 = 0xb430b0edca37c8dbULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_msgs/RunBehaviorResult";
  }

  static const char* value(const  ::nao_msgs::RunBehaviorResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool noErrors\n\
\n\
";
  }

  static const char* value(const  ::nao_msgs::RunBehaviorResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.noErrors);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RunBehaviorResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_msgs::RunBehaviorResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nao_msgs::RunBehaviorResult_<ContainerAllocator> & v) 
  {
    s << indent << "noErrors: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.noErrors);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NAO_MSGS_MESSAGE_RUNBEHAVIORRESULT_H

