/* Auto-generated by genmsg_cpp for file /home/rob/ros_workspace/rosmodules/nao/stacks/nao_robot/nao_msgs/msg/TorsoOdometry.msg */
#ifndef NAO_MSGS_MESSAGE_TORSOODOMETRY_H
#define NAO_MSGS_MESSAGE_TORSOODOMETRY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace nao_msgs
{
template <class ContainerAllocator>
struct TorsoOdometry_ {
  typedef TorsoOdometry_<ContainerAllocator> Type;

  TorsoOdometry_()
  : header()
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , wx(0.0)
  , wy(0.0)
  , wz(0.0)
  {
  }

  TorsoOdometry_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , wx(0.0)
  , wy(0.0)
  , wz(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef float _wx_type;
  float wx;

  typedef float _wy_type;
  float wy;

  typedef float _wz_type;
  float wz;


  typedef boost::shared_ptr< ::nao_msgs::TorsoOdometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_msgs::TorsoOdometry_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TorsoOdometry
typedef  ::nao_msgs::TorsoOdometry_<std::allocator<void> > TorsoOdometry;

typedef boost::shared_ptr< ::nao_msgs::TorsoOdometry> TorsoOdometryPtr;
typedef boost::shared_ptr< ::nao_msgs::TorsoOdometry const> TorsoOdometryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nao_msgs::TorsoOdometry_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nao_msgs::TorsoOdometry_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nao_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::TorsoOdometry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nao_msgs::TorsoOdometry_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nao_msgs::TorsoOdometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1f66dc501c9b69278147e3b32257e58c";
  }

  static const char* value(const  ::nao_msgs::TorsoOdometry_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1f66dc501c9b6927ULL;
  static const uint64_t static_value2 = 0x8147e3b32257e58cULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_msgs::TorsoOdometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nao_msgs/TorsoOdometry";
  }

  static const char* value(const  ::nao_msgs::TorsoOdometry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nao_msgs::TorsoOdometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Data from Nao's torso odometry estimate based on joint kinematics\n\
#\n\
# x, y, z: position of torso in odometry frame\n\
# wx, wy, wz: attitude of torso around x, y, z axis\n\
\n\
Header header\n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 wx\n\
float32 wy\n\
float32 wz\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::nao_msgs::TorsoOdometry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::nao_msgs::TorsoOdometry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::nao_msgs::TorsoOdometry_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nao_msgs::TorsoOdometry_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.wx);
    stream.next(m.wy);
    stream.next(m.wz);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TorsoOdometry_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_msgs::TorsoOdometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nao_msgs::TorsoOdometry_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "wx: ";
    Printer<float>::stream(s, indent + "  ", v.wx);
    s << indent << "wy: ";
    Printer<float>::stream(s, indent + "  ", v.wy);
    s << indent << "wz: ";
    Printer<float>::stream(s, indent + "  ", v.wz);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NAO_MSGS_MESSAGE_TORSOODOMETRY_H

