/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class BVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_BVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BVector() {
    this(yarpJNI.new_BVector__SWIG_0(), true);
  }

  public BVector(long n) {
    this(yarpJNI.new_BVector__SWIG_1(n), true);
  }

  public long size() {
    return yarpJNI.BVector_size(swigCPtr, this);
  }

  public long capacity() {
    return yarpJNI.BVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    yarpJNI.BVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return yarpJNI.BVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    yarpJNI.BVector_clear(swigCPtr, this);
  }

  public void add(boolean x) {
    yarpJNI.BVector_add(swigCPtr, this, x);
  }

  public boolean get(int i) {
    return yarpJNI.BVector_get(swigCPtr, this, i);
  }

  public void set(int i, boolean val) {
    yarpJNI.BVector_set(swigCPtr, this, i, val);
  }

}
