/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Contactable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Contactable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Contactable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Contactable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean open() {
    return yarpJNI.Contactable_open__SWIG_0(swigCPtr, this);
  }

  public boolean open(String name) {
    return yarpJNI.Contactable_open__SWIG_1(swigCPtr, this, name);
  }

  public boolean open(Contact contact, boolean registerName) {
    return yarpJNI.Contactable_open__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact, registerName);
  }

  public boolean open(Contact contact) {
    return yarpJNI.Contactable_open__SWIG_3(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public boolean addOutput(String name) {
    return yarpJNI.Contactable_addOutput__SWIG_0(swigCPtr, this, name);
  }

  public boolean addOutput(String name, String carrier) {
    return yarpJNI.Contactable_addOutput__SWIG_1(swigCPtr, this, name, carrier);
  }

  public boolean addOutput(Contact contact) {
    return yarpJNI.Contactable_addOutput__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public void close() {
    yarpJNI.Contactable_close(swigCPtr, this);
  }

  public void interrupt() {
    yarpJNI.Contactable_interrupt(swigCPtr, this);
  }

  public void resume() {
    yarpJNI.Contactable_resume(swigCPtr, this);
  }

  public Contact where() {
    return new Contact(yarpJNI.Contactable_where(swigCPtr, this), true);
  }

  public String getName() {
    return yarpJNI.Contactable_getName(swigCPtr, this);
  }

  public boolean setEnvelope(PortWriter envelope) {
    return yarpJNI.Contactable_setEnvelope(swigCPtr, this, PortWriter.getCPtr(envelope), envelope);
  }

  public boolean getEnvelope(PortReader envelope) {
    return yarpJNI.Contactable_getEnvelope(swigCPtr, this, PortReader.getCPtr(envelope), envelope);
  }

  public int getInputCount() {
    return yarpJNI.Contactable_getInputCount(swigCPtr, this);
  }

  public int getOutputCount() {
    return yarpJNI.Contactable_getOutputCount(swigCPtr, this);
  }

  public void getReport(PortReport reporter) {
    yarpJNI.Contactable_getReport(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public void setReporter(PortReport reporter) {
    yarpJNI.Contactable_setReporter(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public boolean isWriting() {
    return yarpJNI.Contactable_isWriting(swigCPtr, this);
  }

  public void setReader(PortReader reader) {
    yarpJNI.Contactable_setReader(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setInputMode(boolean expectInput) {
    yarpJNI.Contactable_setInputMode(swigCPtr, this, expectInput);
  }

  public void setOutputMode(boolean expectOutput) {
    yarpJNI.Contactable_setOutputMode(swigCPtr, this, expectOutput);
  }

  public void setRpcMode(boolean expectRpc) {
    yarpJNI.Contactable_setRpcMode(swigCPtr, this, expectRpc);
  }

  public SWIGTYPE_p_Type getType() {
    return new SWIGTYPE_p_Type(yarpJNI.Contactable_getType(swigCPtr, this), true);
  }

  public void promiseType(SWIGTYPE_p_Type typ) {
    yarpJNI.Contactable_promiseType(swigCPtr, this, SWIGTYPE_p_Type.getCPtr(typ));
  }

  public Property acquireProperties(boolean readOnly) {
    long cPtr = yarpJNI.Contactable_acquireProperties(swigCPtr, this, readOnly);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public void releaseProperties(Property prop) {
    yarpJNI.Contactable_releaseProperties(swigCPtr, this, Property.getCPtr(prop), prop);
  }

  public void includeNodeInName(boolean flag) {
    yarpJNI.Contactable_includeNodeInName(swigCPtr, this, flag);
  }

  public void setReadOnly() {
    yarpJNI.Contactable_setReadOnly(swigCPtr, this);
  }

  public void setWriteOnly() {
    yarpJNI.Contactable_setWriteOnly(swigCPtr, this);
  }

  public void setRpcServer() {
    yarpJNI.Contactable_setRpcServer(swigCPtr, this);
  }

  public void setRpcClient() {
    yarpJNI.Contactable_setRpcClient(swigCPtr, this);
  }

}
