/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Drivers {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Drivers(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Drivers obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Drivers(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Drivers factory() {
    return new Drivers(yarpJNI.Drivers_factory(), false);
  }

  public DeviceDriver open(String device) {
    long cPtr = yarpJNI.Drivers_open__SWIG_0(swigCPtr, this, device);
    return (cPtr == 0) ? null : new DeviceDriver(cPtr, false);
  }

  public DeviceDriver open(Searchable config) {
    long cPtr = yarpJNI.Drivers_open__SWIG_1(swigCPtr, this, Searchable.getCPtr(config), config);
    return (cPtr == 0) ? null : new DeviceDriver(cPtr, false);
  }

  public String toString_c() {
    return yarpJNI.Drivers_toString_c(swigCPtr, this);
  }

  public void add(DriverCreator creator) {
    yarpJNI.Drivers_add(swigCPtr, this, DriverCreator.getCPtr(creator), creator);
  }

  public DriverCreator find(String name) {
    long cPtr = yarpJNI.Drivers_find(swigCPtr, this, name);
    return (cPtr == 0) ? null : new DriverCreator(cPtr, false);
  }

  public boolean remove(String name) {
    return yarpJNI.Drivers_remove(swigCPtr, this, name);
  }

  public static int yarpdev(int argc, SWIGTYPE_p_p_char argv) {
    return yarpJNI.Drivers_yarpdev(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

}
