/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class FlexImage extends Image {
  private long swigCPtr;

  protected FlexImage(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.FlexImage_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FlexImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_FlexImage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setPixelCode(int imgPixelCode) {
    yarpJNI.FlexImage_setPixelCode(swigCPtr, this, imgPixelCode);
  }

  public void setPixelSize(int imgPixelSize) {
    yarpJNI.FlexImage_setPixelSize(swigCPtr, this, imgPixelSize);
  }

  public void setQuantum(int imgQuantum) {
    yarpJNI.FlexImage_setQuantum(swigCPtr, this, imgQuantum);
  }

  public FlexImage() {
    this(yarpJNI.new_FlexImage(), true);
  }

}
