/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IControlCalibration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IControlCalibration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IControlCalibration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IControlCalibration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean calibrate(int j, double p) {
    return yarpJNI.IControlCalibration_calibrate__SWIG_0(swigCPtr, this, j, p);
  }

  public boolean done(int j) {
    return yarpJNI.IControlCalibration_done(swigCPtr, this, j);
  }

  public boolean setCalibrator(SWIGTYPE_p_ICalibrator c) {
    return yarpJNI.IControlCalibration_setCalibrator(swigCPtr, this, SWIGTYPE_p_ICalibrator.getCPtr(c));
  }

  public boolean calibrate() {
    return yarpJNI.IControlCalibration_calibrate__SWIG_1(swigCPtr, this);
  }

  public boolean park(boolean wait) {
    return yarpJNI.IControlCalibration_park__SWIG_0(swigCPtr, this, wait);
  }

  public boolean park() {
    return yarpJNI.IControlCalibration_park__SWIG_1(swigCPtr, this);
  }

}
