/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IEncoders {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IEncoders(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IEncoders obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IEncoders(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getAxes(SWIGTYPE_p_int ax) {
    return yarpJNI.IEncoders_getAxes__SWIG_0(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ax));
  }

  public boolean resetEncoder(int j) {
    return yarpJNI.IEncoders_resetEncoder(swigCPtr, this, j);
  }

  public boolean resetEncoders() {
    return yarpJNI.IEncoders_resetEncoders(swigCPtr, this);
  }

  public boolean setEncoder(int j, double val) {
    return yarpJNI.IEncoders_setEncoder(swigCPtr, this, j, val);
  }

  public boolean setEncoders(SWIGTYPE_p_double vals) {
    return yarpJNI.IEncoders_setEncoders__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(vals));
  }

  public boolean getEncoder(int j, SWIGTYPE_p_double v) {
    return yarpJNI.IEncoders_getEncoder__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(v));
  }

  public boolean getEncoders(SWIGTYPE_p_double encs) {
    return yarpJNI.IEncoders_getEncoders__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(encs));
  }

  public boolean getEncoderSpeed(int j, SWIGTYPE_p_double sp) {
    return yarpJNI.IEncoders_getEncoderSpeed__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(sp));
  }

  public boolean getEncoderSpeeds(SWIGTYPE_p_double spds) {
    return yarpJNI.IEncoders_getEncoderSpeeds__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(spds));
  }

  public boolean getEncoderAcceleration(int j, SWIGTYPE_p_double spds) {
    return yarpJNI.IEncoders_getEncoderAcceleration__SWIG_0(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(spds));
  }

  public boolean getEncoderAccelerations(SWIGTYPE_p_double accs) {
    return yarpJNI.IEncoders_getEncoderAccelerations__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(accs));
  }

  public int getAxes() {
    return yarpJNI.IEncoders_getAxes__SWIG_1(swigCPtr, this);
  }

  public boolean setEncoders(DVector data) {
    return yarpJNI.IEncoders_setEncoders__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public double getEncoder(int j) {
    return yarpJNI.IEncoders_getEncoder__SWIG_1(swigCPtr, this, j);
  }

  public boolean getEncoders(DVector data) {
    return yarpJNI.IEncoders_getEncoders__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public double getEncoderSpeed(int j) {
    return yarpJNI.IEncoders_getEncoderSpeed__SWIG_1(swigCPtr, this, j);
  }

  public boolean getEncoderSpeeds(DVector data) {
    return yarpJNI.IEncoders_getEncoderSpeeds__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

  public double getEncoderAcceleration(int j) {
    return yarpJNI.IEncoders_getEncoderAcceleration__SWIG_1(swigCPtr, this, j);
  }

  public boolean getEncoderAccelerations(DVector data) {
    return yarpJNI.IEncoders_getEncoderAccelerations__SWIG_1(swigCPtr, this, DVector.getCPtr(data), data);
  }

}
