/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class IEncodersRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IEncodersRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IEncodersRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_IEncodersRaw(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getAxes(SWIGTYPE_p_int ax) {
    return yarpJNI.IEncodersRaw_getAxes(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ax));
  }

  public boolean resetEncoderRaw(int j) {
    return yarpJNI.IEncodersRaw_resetEncoderRaw(swigCPtr, this, j);
  }

  public boolean resetEncodersRaw() {
    return yarpJNI.IEncodersRaw_resetEncodersRaw(swigCPtr, this);
  }

  public boolean setEncoderRaw(int j, double val) {
    return yarpJNI.IEncodersRaw_setEncoderRaw(swigCPtr, this, j, val);
  }

  public boolean setEncodersRaw(SWIGTYPE_p_double vals) {
    return yarpJNI.IEncodersRaw_setEncodersRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(vals));
  }

  public boolean getEncoderRaw(int j, SWIGTYPE_p_double v) {
    return yarpJNI.IEncodersRaw_getEncoderRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(v));
  }

  public boolean getEncodersRaw(SWIGTYPE_p_double encs) {
    return yarpJNI.IEncodersRaw_getEncodersRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(encs));
  }

  public boolean getEncoderSpeedRaw(int j, SWIGTYPE_p_double sp) {
    return yarpJNI.IEncodersRaw_getEncoderSpeedRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(sp));
  }

  public boolean getEncoderSpeedsRaw(SWIGTYPE_p_double spds) {
    return yarpJNI.IEncodersRaw_getEncoderSpeedsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(spds));
  }

  public boolean getEncoderAccelerationRaw(int j, SWIGTYPE_p_double spds) {
    return yarpJNI.IEncodersRaw_getEncoderAccelerationRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(spds));
  }

  public boolean getEncoderAccelerationsRaw(SWIGTYPE_p_double accs) {
    return yarpJNI.IEncodersRaw_getEncoderAccelerationsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(accs));
  }

}
