/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ImageRgb extends Image {
  private long swigCPtr;

  protected ImageRgb(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.ImageRgb_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageRgb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ImageRgb(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getPixelSize() {
    return yarpJNI.ImageRgb_getPixelSize(swigCPtr, this);
  }

  public int getPixelCode() {
    return yarpJNI.ImageRgb_getPixelCode(swigCPtr, this);
  }

  public PixelRgb pixel(int x, int y) {
    return new PixelRgb(yarpJNI.ImageRgb_pixel(swigCPtr, this, x, y), false);
  }

  public PixelRgb access(int x, int y) {
    return new PixelRgb(yarpJNI.ImageRgb_access(swigCPtr, this, x, y), false);
  }

  public PixelRgb safePixel(int x, int y) {
    return new PixelRgb(yarpJNI.ImageRgb_safePixel__SWIG_0(swigCPtr, this, x, y), false);
  }

  public ImageRgb() {
    this(yarpJNI.new_ImageRgb(), true);
  }

}
