/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class ITorqueControlRaw {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ITorqueControlRaw(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITorqueControlRaw obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_ITorqueControlRaw(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean getAxes(SWIGTYPE_p_int ax) {
    return yarpJNI.ITorqueControlRaw_getAxes(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ax));
  }

  public boolean setTorqueModeRaw() {
    return yarpJNI.ITorqueControlRaw_setTorqueModeRaw(swigCPtr, this);
  }

  public boolean getTorqueRaw(int j, SWIGTYPE_p_double t) {
    return yarpJNI.ITorqueControlRaw_getTorqueRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean getTorquesRaw(SWIGTYPE_p_double t) {
    return yarpJNI.ITorqueControlRaw_getTorquesRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean getTorqueRangeRaw(int j, SWIGTYPE_p_double min, SWIGTYPE_p_double max) {
    return yarpJNI.ITorqueControlRaw_getTorqueRangeRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(min), SWIGTYPE_p_double.getCPtr(max));
  }

  public boolean getTorqueRangesRaw(SWIGTYPE_p_double min, SWIGTYPE_p_double max) {
    return yarpJNI.ITorqueControlRaw_getTorqueRangesRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(min), SWIGTYPE_p_double.getCPtr(max));
  }

  public boolean setRefTorquesRaw(SWIGTYPE_p_double t) {
    return yarpJNI.ITorqueControlRaw_setRefTorquesRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean setRefTorqueRaw(int j, double t) {
    return yarpJNI.ITorqueControlRaw_setRefTorqueRaw(swigCPtr, this, j, t);
  }

  public boolean getRefTorquesRaw(SWIGTYPE_p_double t) {
    return yarpJNI.ITorqueControlRaw_getRefTorquesRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean getRefTorqueRaw(int j, SWIGTYPE_p_double t) {
    return yarpJNI.ITorqueControlRaw_getRefTorqueRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(t));
  }

  public boolean getBemfParamRaw(int j, SWIGTYPE_p_double bemf) {
    return yarpJNI.ITorqueControlRaw_getBemfParamRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(bemf));
  }

  public boolean setBemfParamRaw(int j, double bemf) {
    return yarpJNI.ITorqueControlRaw_setBemfParamRaw(swigCPtr, this, j, bemf);
  }

  public boolean setTorquePidRaw(int j, Pid pid) {
    return yarpJNI.ITorqueControlRaw_setTorquePidRaw(swigCPtr, this, j, Pid.getCPtr(pid), pid);
  }

  public boolean setTorquePidsRaw(Pid pids) {
    return yarpJNI.ITorqueControlRaw_setTorquePidsRaw(swigCPtr, this, Pid.getCPtr(pids), pids);
  }

  public boolean setTorqueErrorLimitRaw(int j, double limit) {
    return yarpJNI.ITorqueControlRaw_setTorqueErrorLimitRaw(swigCPtr, this, j, limit);
  }

  public boolean setTorqueErrorLimitsRaw(SWIGTYPE_p_double limits) {
    return yarpJNI.ITorqueControlRaw_setTorqueErrorLimitsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(limits));
  }

  public boolean getTorqueErrorRaw(int j, SWIGTYPE_p_double err) {
    return yarpJNI.ITorqueControlRaw_getTorqueErrorRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(err));
  }

  public boolean getTorqueErrorsRaw(SWIGTYPE_p_double errs) {
    return yarpJNI.ITorqueControlRaw_getTorqueErrorsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(errs));
  }

  public boolean getTorquePidOutputRaw(int j, SWIGTYPE_p_double out) {
    return yarpJNI.ITorqueControlRaw_getTorquePidOutputRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(out));
  }

  public boolean getTorquePidOutputsRaw(SWIGTYPE_p_double outs) {
    return yarpJNI.ITorqueControlRaw_getTorquePidOutputsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(outs));
  }

  public boolean getTorquePidRaw(int j, Pid pid) {
    return yarpJNI.ITorqueControlRaw_getTorquePidRaw(swigCPtr, this, j, Pid.getCPtr(pid), pid);
  }

  public boolean getTorquePidsRaw(Pid pids) {
    return yarpJNI.ITorqueControlRaw_getTorquePidsRaw(swigCPtr, this, Pid.getCPtr(pids), pids);
  }

  public boolean getTorqueErrorLimitRaw(int j, SWIGTYPE_p_double limit) {
    return yarpJNI.ITorqueControlRaw_getTorqueErrorLimitRaw(swigCPtr, this, j, SWIGTYPE_p_double.getCPtr(limit));
  }

  public boolean getTorqueErrorLimitsRaw(SWIGTYPE_p_double limits) {
    return yarpJNI.ITorqueControlRaw_getTorqueErrorLimitsRaw(swigCPtr, this, SWIGTYPE_p_double.getCPtr(limits));
  }

  public boolean resetTorquePidRaw(int j) {
    return yarpJNI.ITorqueControlRaw_resetTorquePidRaw(swigCPtr, this, j);
  }

  public boolean disableTorquePidRaw(int j) {
    return yarpJNI.ITorqueControlRaw_disableTorquePidRaw(swigCPtr, this, j);
  }

  public boolean enableTorquePidRaw(int j) {
    return yarpJNI.ITorqueControlRaw_enableTorquePidRaw(swigCPtr, this, j);
  }

  public boolean setTorqueOffsetRaw(int j, double v) {
    return yarpJNI.ITorqueControlRaw_setTorqueOffsetRaw(swigCPtr, this, j, v);
  }

}
