/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class PortWriterBufferBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PortWriterBufferBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PortWriterBufferBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_PortWriterBufferBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PortWriterWrapper create(PortWriterBufferManager man, SWIGTYPE_p_void tracker) {
    long cPtr = yarpJNI.PortWriterBufferBase_create(swigCPtr, this, PortWriterBufferManager.getCPtr(man), man, SWIGTYPE_p_void.getCPtr(tracker));
    return (cPtr == 0) ? null : new PortWriterWrapper(cPtr, false);
  }

  public SWIGTYPE_p_void getContent() {
    long cPtr = yarpJNI.PortWriterBufferBase_getContent(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public boolean releaseContent() {
    return yarpJNI.PortWriterBufferBase_releaseContent(swigCPtr, this);
  }

  public int getCount() {
    return yarpJNI.PortWriterBufferBase_getCount(swigCPtr, this);
  }

  public void attach(Port port) {
    yarpJNI.PortWriterBufferBase_attach(swigCPtr, this, Port.getCPtr(port), port);
  }

  public void detach() {
    yarpJNI.PortWriterBufferBase_detach(swigCPtr, this);
  }

  public void write(boolean strict) {
    yarpJNI.PortWriterBufferBase_write(swigCPtr, this, strict);
  }

  public void waitForWrite() {
    yarpJNI.PortWriterBufferBase_waitForWrite(swigCPtr, this);
  }

}
