/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Random {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Random(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Random obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Random(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double uniform() {
    return yarpJNI.Random_uniform__SWIG_0();
  }

  public static double normal(double m, double s) {
    return yarpJNI.Random_normal__SWIG_0(m, s);
  }

  public static void seed_c(int seed) {
    yarpJNI.Random_seed_c(seed);
  }

  public static double normal() {
    return yarpJNI.Random_normal__SWIG_1();
  }

  public static int uniform(int min, int max) {
    return yarpJNI.Random_uniform__SWIG_1(min, max);
  }

  public Random() {
    this(yarpJNI.new_Random(), true);
  }

}
