/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class SearchReport {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SearchReport(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SearchReport obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_SearchReport(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKey(String value) {
    yarpJNI.SearchReport_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return yarpJNI.SearchReport_key_get(swigCPtr, this);
  }

  public void setValue(String value) {
    yarpJNI.SearchReport_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return yarpJNI.SearchReport_value_get(swigCPtr, this);
  }

  public void setIsFound(boolean value) {
    yarpJNI.SearchReport_isFound_set(swigCPtr, this, value);
  }

  public boolean getIsFound() {
    return yarpJNI.SearchReport_isFound_get(swigCPtr, this);
  }

  public void setIsGroup(boolean value) {
    yarpJNI.SearchReport_isGroup_set(swigCPtr, this, value);
  }

  public boolean getIsGroup() {
    return yarpJNI.SearchReport_isGroup_get(swigCPtr, this);
  }

  public void setIsComment(boolean value) {
    yarpJNI.SearchReport_isComment_set(swigCPtr, this, value);
  }

  public boolean getIsComment() {
    return yarpJNI.SearchReport_isComment_get(swigCPtr, this);
  }

  public void setIsDefault(boolean value) {
    yarpJNI.SearchReport_isDefault_set(swigCPtr, this, value);
  }

  public boolean getIsDefault() {
    return yarpJNI.SearchReport_isDefault_get(swigCPtr, this);
  }

  public SearchReport() {
    this(yarpJNI.new_SearchReport(), true);
  }

}
