/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class StubDriverCreator extends DriverCreator {
  private long swigCPtr;

  protected StubDriverCreator(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.StubDriverCreator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StubDriverCreator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_StubDriverCreator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StubDriverCreator(String name, String wrap, String code, String libname) {
    this(yarpJNI.new_StubDriverCreator(name, wrap, code, libname), true);
  }

  public String toString_c() {
    return yarpJNI.StubDriverCreator_toString_c(swigCPtr, this);
  }

  public String getName() {
    return yarpJNI.StubDriverCreator_getName(swigCPtr, this);
  }

  public String getWrapper() {
    return yarpJNI.StubDriverCreator_getWrapper(swigCPtr, this);
  }

  public String getCode() {
    return yarpJNI.StubDriverCreator_getCode(swigCPtr, this);
  }

  public DeviceDriver create() {
    long cPtr = yarpJNI.StubDriverCreator_create(swigCPtr, this);
    return (cPtr == 0) ? null : new DeviceDriver(cPtr, false);
  }

}
