/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Things {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Things(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Things obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Things(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Things() {
    this(yarpJNI.new_Things(), true);
  }

  public void setPortWriter(PortWriter writer) {
    yarpJNI.Things_setPortWriter(swigCPtr, this, PortWriter.getCPtr(writer), writer);
  }

  public PortWriter getPortWriter() {
    long cPtr = yarpJNI.Things_getPortWriter(swigCPtr, this);
    return (cPtr == 0) ? null : new PortWriter(cPtr, false);
  }

  public boolean setConnectionReader(ConnectionReader reader) {
    return yarpJNI.Things_setConnectionReader(swigCPtr, this, ConnectionReader.getCPtr(reader), reader);
  }

  public boolean write(ConnectionWriter connection) {
    return yarpJNI.Things_write(swigCPtr, this, ConnectionWriter.getCPtr(connection), connection);
  }

  public void reset() {
    yarpJNI.Things_reset(swigCPtr, this);
  }

  public void setConReader(ConnectionReader value) {
    yarpJNI.Things_conReader_set(swigCPtr, this, ConnectionReader.getCPtr(value), value);
  }

  public ConnectionReader getConReader() {
    long cPtr = yarpJNI.Things_conReader_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConnectionReader(cPtr, false);
  }

  public void setWriter(PortWriter value) {
    yarpJNI.Things_writer_set(swigCPtr, this, PortWriter.getCPtr(value), value);
  }

  public PortWriter getWriter() {
    long cPtr = yarpJNI.Things_writer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PortWriter(cPtr, false);
  }

  public void setPortable(Portable value) {
    yarpJNI.Things_portable_set(swigCPtr, this, Portable.getCPtr(value), value);
  }

  public Portable getPortable() {
    long cPtr = yarpJNI.Things_portable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Portable(cPtr, false);
  }

  public Value asValue() {
    long cPtr = yarpJNI.Things_asValue(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Bottle asBottle() {
    long cPtr = yarpJNI.Things_asBottle(swigCPtr, this);
    return (cPtr == 0) ? null : new Bottle(cPtr, false);
  }

  public Property asProperty() {
    long cPtr = yarpJNI.Things_asProperty(swigCPtr, this);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public Vector asVector() {
    long cPtr = yarpJNI.Things_asVector(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector(cPtr, false);
  }

  public SWIGTYPE_p_yarp__sig__Matrix asMatrix() {
    long cPtr = yarpJNI.Things_asMatrix(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_yarp__sig__Matrix(cPtr, false);
  }

  public Image asImage() {
    long cPtr = yarpJNI.Things_asImage(swigCPtr, this);
    return (cPtr == 0) ? null : new Image(cPtr, false);
  }

  public ImageRgb asImageOfPixelRgb() {
    long cPtr = yarpJNI.Things_asImageOfPixelRgb(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgb(cPtr, false);
  }

  public SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t asImageOfPixelBgr() {
    long cPtr = yarpJNI.Things_asImageOfPixelBgr(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t(cPtr, false);
  }

  public ImageMono asImageOfPixelMono() {
    long cPtr = yarpJNI.Things_asImageOfPixelMono(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageMono(cPtr, false);
  }

}
