/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Time {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Time(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void delay(double seconds) {
    yarpJNI.Time_delay(seconds);
  }

  public static double now() {
    return yarpJNI.Time_now();
  }

  public static void yield() {
    yarpJNI.Time_yield();
  }

  public static void turboBoost() {
    yarpJNI.Time_turboBoost();
  }

  public static void useSystemClock() {
    yarpJNI.Time_useSystemClock();
  }

  public static void useNetworkClock(String clock) {
    yarpJNI.Time_useNetworkClock(clock);
  }

  public static void useCustomClock(SWIGTYPE_p_Clock clock) {
    yarpJNI.Time_useCustomClock(SWIGTYPE_p_Clock.getCPtr(clock));
  }

  public static boolean isSystemClock() {
    return yarpJNI.Time_isSystemClock();
  }

  public static boolean isValid() {
    return yarpJNI.Time_isValid();
  }

  public Time() {
    this(yarpJNI.new_Time(), true);
  }

}
