/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class VectorBase extends Portable {
  private long swigCPtr;

  protected VectorBase(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.VectorBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_VectorBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getElementSize() {
    return yarpJNI.VectorBase_getElementSize(swigCPtr, this);
  }

  public long getListSize() {
    return yarpJNI.VectorBase_getListSize(swigCPtr, this);
  }

  public String getMemoryBlock() {
    return yarpJNI.VectorBase_getMemoryBlock(swigCPtr, this);
  }

  public void resize(long size) {
    yarpJNI.VectorBase_resize(swigCPtr, this, size);
  }

  public boolean read(ConnectionReader connection) {
    return yarpJNI.VectorBase_read(swigCPtr, this, ConnectionReader.getCPtr(connection), connection);
  }

  public boolean write(ConnectionWriter connection) {
    return yarpJNI.VectorBase_write(swigCPtr, this, ConnectionWriter.getCPtr(connection), connection);
  }

}
