/*******************************************************************************
 * Copyright (C) 2009-2020 Human Media Interaction, University of Twente, the Netherlands
 *
 * This file is part of the Articulated Social Agents Platform BML realizer (ASAPRealizer).
 *
 * ASAPRealizer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ASAPRealizer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with ASAPRealizer.  If not, see http://www.gnu.org/licenses/.
 ******************************************************************************/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public interface yarpConstants {
  public final static int YARP_CONSTSTRING_IS_STD_STRING = yarpJNI.YARP_CONSTSTRING_IS_STD_STRING_get();
  public final static int BOTTLE_TAG_INT = yarpJNI.BOTTLE_TAG_INT_get();
  public final static int BOTTLE_TAG_VOCAB = yarpJNI.BOTTLE_TAG_VOCAB_get();
  public final static int BOTTLE_TAG_DOUBLE = yarpJNI.BOTTLE_TAG_DOUBLE_get();
  public final static int BOTTLE_TAG_STRING = yarpJNI.BOTTLE_TAG_STRING_get();
  public final static int BOTTLE_TAG_BLOB = yarpJNI.BOTTLE_TAG_BLOB_get();
  public final static int BOTTLE_TAG_LIST = yarpJNI.BOTTLE_TAG_LIST_get();
  public final static int BOTTLE_TAG_DICT = yarpJNI.BOTTLE_TAG_DICT_get();
  public final static int FORMAT_NULL = yarpJNI.FORMAT_NULL_get();
  public final static int FORMAT_ANY = yarpJNI.FORMAT_ANY_get();
  public final static int FORMAT_PGM = yarpJNI.FORMAT_PGM_get();
  public final static int FORMAT_PPM = yarpJNI.FORMAT_PPM_get();
  public final static int FORMAT_NUMERIC = yarpJNI.FORMAT_NUMERIC_get();

}
